Test sdist

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,140 +4,140 @@ on:
   workflow_dispatch:
 
 jobs:
-  wheels:
-    name: ${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest, windows-latest, macos-12]
-        arch: [native]
-        py: [cp37, cp38, cp39, cp310, cp311]
-        # exclude:
-        #     - os: macos-12
-        #       arch: arm64
-        #       py: cp37
-        #     - os: macos-12
-        #       arch: arm64
-        #       py: cp38
-        # os: [ubuntu-latest, windows-latest, macos-12]
-        # os: [ubuntu-latest, windows-latest]
-        # arch: [native, arm64]
-        # py: [cp37, cp38, cp39, cp310]
-    steps:
-
-
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-
-      # graphviz is needed for tests, only install it when compilation succeed
-      # How to integrate into cibuildwheels?
-      - uses: tlylt/install-graphviz@v1
-
-      # Remove after January 16th 2023 when GA switches to 14.2 by default
-      - if: ${{ matrix.os == 'macos-12' }}
-        run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
-
-      - if: ${{ matrix.os == 'macos-12' &&  matrix.arch == 'native'}}
-        name: Setup gfortran for Macos
-        run: |
-          set -xe
-          # Taken from https://github.com/numpy/numpy/tree/main/tools/wheels
-          chmod +x .github/workflows/gfortran_utils.sh
-          source .github/workflows/gfortran_utils.sh
-          install_gfortran
-          gfortran --version
-          which gfortran
-
-
-      - if: ${{ matrix.arch == 'aarch64' }}
-        uses: docker/setup-qemu-action@v2
-
-      - if: ${{ matrix.os != 'macos-12' }}
-        uses: awvwgk/setup-fortran@main
-        id: setup-fortran
-        with:
-          compiler: gcc
-          version: 11
-
-      - if: ${{ matrix.os == 'windows-latest' }}
-        uses: pypa/cibuildwheel@v2.11.2
-        env:
-          CIBW_BUILD_VERBOSITY: 3
-          CIBW_BUILD: ${{ matrix.py }}-*
-          CIBW_ARCHS: ${{ matrix.arch }}
-          CIBW_SKIP: "*musllinux*"
-          CMAKE_GENERATOR: "MinGW Makefiles"
-          FC: ${{ steps.setup-fortran.outputs.fc }}
-
-      - if: ${{ matrix.os == 'ubuntu-latest' }}
-        uses: pypa/cibuildwheel@v2.11.2
-        env:
-          # Check setuptools version
-          CIBW_BUILD_VERBOSITY: 3
-          CIBW_BUILD: ${{ matrix.py }}-*
-          CIBW_ARCHS: ${{ matrix.arch }}
-          CIBW_SKIP: "*musllinux*"
-
-      - if: ${{ matrix.os == 'macos-12' &&  matrix.arch == 'native' }}
-        uses: pypa/cibuildwheel@v2.11.2
-        env:
-          # Check setuptools version
-          CIBW_BUILD_VERBOSITY: 3
-          CIBW_BUILD: ${{ matrix.py }}-*
-          CIBW_ARCHS: ${{ matrix.arch }}
-          CIBW_SKIP: "*musllinux*"
-          no_proxy: '*'
-
-      - if: ${{ matrix.os == 'macos-12' &&  matrix.arch == 'arm64' }}
-        id: cibw_step
-        uses: pypa/cibuildwheel@v2.11.2
-        env:
-          # Check setuptools version
-          CIBW_BUILD_VERBOSITY: 3
-          CIBW_BUILD: ${{ matrix.py }}-*
-          CIBW_ARCHS: ${{ matrix.arch }}
-          CIBW_SKIP: "*musllinux*"
-          CIBW_TEST_SKIP: "*_arm64 *_universal2:arm64"
-          CIBW_ARCHS_MACOS: arm64
-          CIBW_BEFORE_BUILD: |
-            set -xe
-            # Taken from https://github.com/numpy/numpy/tree/main/tools/wheels
-            export PLAT="arm64"
-            chmod +x .github/workflows/gfortran_utils.sh
-            source .github/workflows/gfortran_utils.sh
-            install_arm64_cross_gfortran
-          FC: "/opt/gfortran-darwin-arm64-cross/bin/arm64-apple-darwin20.0.0-gfortran"
-          MACOSX_DEPLOYMENT_TARGET: "11.0"
-          no_proxy: '*'
-
-      - uses: actions/upload-artifact@v3
-        with:
-          path: ./wheelhouse/*.whl
-
-  # sdist:
-  #   name: source package
-  #   runs-on: ubuntu-latest
+  # wheels:
+  #   name: ${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }}
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-latest, windows-latest, macos-12]
+  #       arch: [native]
+  #       py: [cp37, cp38, cp39, cp310, cp311]
+  #       # exclude:
+  #       #     - os: macos-12
+  #       #       arch: arm64
+  #       #       py: cp37
+  #       #     - os: macos-12
+  #       #       arch: arm64
+  #       #       py: cp38
+  #       # os: [ubuntu-latest, windows-latest, macos-12]
+  #       # os: [ubuntu-latest, windows-latest]
+  #       # arch: [native, arm64]
+  #       # py: [cp37, cp38, cp39, cp310]
   #   steps:
+
+
   #     - uses: actions/checkout@v3
   #       with:
   #         submodules: true
 
-  #     - uses: actions/setup-python@v4
-  #       name: Install Python
-  #       with:
-  #         python-version: '3.9'
+  #     # graphviz is needed for tests, only install it when compilation succeed
+  #     # How to integrate into cibuildwheels?
+  #     - uses: tlylt/install-graphviz@v1
 
-  #     - run: python -m pip install --upgrade pip wheel
-  #     - run: python setup.py sdist
-  #     - run: python -m pip install --prefer-binary -v `echo dist/impy-*`[test]
-  #     - run: python -m pip install pytest
-  #     - run: python -m pytest -vv
+  #     # Remove after January 16th 2023 when GA switches to 14.2 by default
+  #     - if: ${{ matrix.os == 'macos-12' }}
+  #       run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
+
+  #     - if: ${{ matrix.os == 'macos-12' &&  matrix.arch == 'native'}}
+  #       name: Setup gfortran for Macos
+  #       run: |
+  #         set -xe
+  #         # Taken from https://github.com/numpy/numpy/tree/main/tools/wheels
+  #         chmod +x .github/workflows/gfortran_utils.sh
+  #         source .github/workflows/gfortran_utils.sh
+  #         install_gfortran
+  #         gfortran --version
+  #         which gfortran
+
+
+  #     - if: ${{ matrix.arch == 'aarch64' }}
+  #       uses: docker/setup-qemu-action@v2
+
+  #     - if: ${{ matrix.os != 'macos-12' }}
+  #       uses: awvwgk/setup-fortran@main
+  #       id: setup-fortran
+  #       with:
+  #         compiler: gcc
+  #         version: 11
+
+  #     - if: ${{ matrix.os == 'windows-latest' }}
+  #       uses: pypa/cibuildwheel@v2.11.2
+  #       env:
+  #         CIBW_BUILD_VERBOSITY: 3
+  #         CIBW_BUILD: ${{ matrix.py }}-*
+  #         CIBW_ARCHS: ${{ matrix.arch }}
+  #         CIBW_SKIP: "*musllinux*"
+  #         CMAKE_GENERATOR: "MinGW Makefiles"
+  #         FC: ${{ steps.setup-fortran.outputs.fc }}
+
+  #     - if: ${{ matrix.os == 'ubuntu-latest' }}
+  #       uses: pypa/cibuildwheel@v2.11.2
+  #       env:
+  #         # Check setuptools version
+  #         CIBW_BUILD_VERBOSITY: 3
+  #         CIBW_BUILD: ${{ matrix.py }}-*
+  #         CIBW_ARCHS: ${{ matrix.arch }}
+  #         CIBW_SKIP: "*musllinux*"
+
+  #     - if: ${{ matrix.os == 'macos-12' &&  matrix.arch == 'native' }}
+  #       uses: pypa/cibuildwheel@v2.11.2
+  #       env:
+  #         # Check setuptools version
+  #         CIBW_BUILD_VERBOSITY: 3
+  #         CIBW_BUILD: ${{ matrix.py }}-*
+  #         CIBW_ARCHS: ${{ matrix.arch }}
+  #         CIBW_SKIP: "*musllinux*"
+  #         no_proxy: '*'
+
+  #     - if: ${{ matrix.os == 'macos-12' &&  matrix.arch == 'arm64' }}
+  #       id: cibw_step
+  #       uses: pypa/cibuildwheel@v2.11.2
+  #       env:
+  #         # Check setuptools version
+  #         CIBW_BUILD_VERBOSITY: 3
+  #         CIBW_BUILD: ${{ matrix.py }}-*
+  #         CIBW_ARCHS: ${{ matrix.arch }}
+  #         CIBW_SKIP: "*musllinux*"
+  #         CIBW_TEST_SKIP: "*_arm64 *_universal2:arm64"
+  #         CIBW_ARCHS_MACOS: arm64
+  #         CIBW_BEFORE_BUILD: |
+  #           set -xe
+  #           # Taken from https://github.com/numpy/numpy/tree/main/tools/wheels
+  #           export PLAT="arm64"
+  #           chmod +x .github/workflows/gfortran_utils.sh
+  #           source .github/workflows/gfortran_utils.sh
+  #           install_arm64_cross_gfortran
+  #         FC: "/opt/gfortran-darwin-arm64-cross/bin/arm64-apple-darwin20.0.0-gfortran"
+  #         MACOSX_DEPLOYMENT_TARGET: "11.0"
+  #         no_proxy: '*'
 
   #     - uses: actions/upload-artifact@v3
   #       with:
-  #         path: dist/*.tar.gz
+  #         path: ./wheelhouse/*.whl
+
+  sdist:
+    name: source package
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          submodules: true
+
+      - uses: actions/setup-python@v4
+        name: Install Python
+        with:
+          python-version: '3.9'
+
+      - run: python -m pip install --upgrade pip wheel
+      - run: python setup.py sdist
+      - run: python -m pip install --prefer-binary -v `echo dist/impy-*`[test]
+      - run: python -m pip install pytest
+      - run: python -m pytest -vv
+
+      - uses: actions/upload-artifact@v3
+        with:
+          path: dist/*.tar.gz
 
   # upload:
   #   needs: [wheels, sdist]
@@ -205,22 +205,22 @@ jobs:
 #     - run: python -m pytest -vv
 
 
-  upload_all_to_TestPyPI:
-    name: Upload to TestPyPI
-    needs: [wheels]
-    runs-on: ubuntu-latest
-    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
-    steps:
-      - name: Download files in artifact to "dist/" directory
-        uses: actions/download-artifact@v3
-        with:
-          name: artifact
-          path: dist
+  # upload_all_to_TestPyPI:
+  #   name: Upload to TestPyPI
+  #   needs: [wheels]
+  #   runs-on: ubuntu-latest
+  #   # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
+  #   steps:
+  #     - name: Download files in artifact to "dist/" directory
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: artifact
+  #         path: dist
 
-      - name: Publish package to TestPyPI
-        uses: pypa/gh-action-pypi-publish@v1.6.4
-        with:
-          user: __token__
-          repository_url: https://test.pypi.org/legacy/
-          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
+  #     - name: Publish package to TestPyPI
+  #       uses: pypa/gh-action-pypi-publish@v1.6.4
+  #       with:
+  #         user: __token__
+  #         repository_url: https://test.pypi.org/legacy/
+  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
 
